// Bridges Pi lifecycle events into cmux's session/notification system.
//
// Source-managed adaptation of the extension generated by `cmux hooks pi install`.
// Keep this in dotfiles instead of letting cmux write directly to ~/.pi/* so the
// Pi profile installer can symlink it into work/personal profiles.

import type {
  AgentEndEvent,
  ExtensionAPI,
  ExtensionContext,
} from "@earendil-works/pi-coding-agent";
import { spawnSync } from "node:child_process";
import * as fs from "node:fs";
import * as path from "node:path";

const firstString = (...values: unknown[]): string | null => {
  for (const value of values) {
    if (typeof value === "string" && value.trim().length > 0) {
      return value.trim();
    }
  }
  return null;
};

const resolveExecutable = (name: string): string => {
  const pathEnv = process.env.PATH || "";
  for (const dir of pathEnv.split(path.delimiter)) {
    if (!dir) continue;
    const candidate = path.join(dir, name);
    try {
      fs.accessSync(candidate, fs.constants.X_OK);
      return candidate;
    } catch {
      // Keep searching PATH.
    }
  }
  return name;
};

const looksLikePiExecutable = (value: string): boolean => {
  const base = path.basename(value).toLowerCase();
  return base === "pi" || base === "pi-coding-agent";
};

const looksLikePiScript = (value: string): boolean => {
  const normalized = value.replaceAll("\\", "/");
  const base = path.basename(normalized).toLowerCase();
  return (
    normalized.includes("/@earendil-works/pi-coding-agent/") ||
    normalized.includes("/@mariozechner/pi-coding-agent/") ||
    normalized.includes("/packages/coding-agent/") ||
    (base === "cli.js" && normalized.includes("pi-coding-agent")) ||
    (base === "cli.ts" && normalized.includes("coding-agent"))
  );
};

const normalizedLaunchArgv = (): string[] => {
  const raw = Array.isArray(process.argv)
    ? process.argv.map((value) => String(value))
    : [];

  if (raw.length === 0) return [resolveExecutable("pi")];
  if (looksLikePiExecutable(raw[0] ?? "")) return raw;
  if (raw.length > 1 && looksLikePiScript(raw[1] ?? "")) {
    return [resolveExecutable("pi"), ...raw.slice(2)];
  }
  return [resolveExecutable("pi"), ...raw.slice(1)];
};

const base64NulSeparated = (values: string[]): string => {
  const bytes: Buffer[] = [];
  for (const value of values) {
    bytes.push(Buffer.from(value, "utf8"));
    bytes.push(Buffer.from([0]));
  }
  return Buffer.concat(bytes).toString("base64");
};

const hookEnvironment = (cwd: string): NodeJS.ProcessEnv => {
  const env: NodeJS.ProcessEnv = { ...process.env };

  // Match cmux's generated extension: do not pass unrelated agent secrets to
  // the hook process.
  delete env.AMP_API_KEY;

  if (!env.CMUX_AGENT_LAUNCH_ARGV_B64) {
    const argv = normalizedLaunchArgv();
    env.CMUX_AGENT_LAUNCH_KIND = "pi";
    env.CMUX_AGENT_LAUNCH_EXECUTABLE = argv[0] || resolveExecutable("pi");
    env.CMUX_AGENT_LAUNCH_ARGV_B64 = base64NulSeparated(argv);
    env.CMUX_AGENT_LAUNCH_CWD = cwd || process.cwd();
  }

  return env;
};

const eventName = (subcommand: string): string => {
  switch (subcommand) {
    case "session-start":
      return "SessionStart";
    case "prompt-submit":
      return "UserPromptSubmit";
    case "stop":
      return "Stop";
    default:
      return subcommand;
  }
};

const textFromContent = (content: unknown): string | null => {
  if (typeof content === "string") return content;
  if (!Array.isArray(content)) return null;

  const parts: string[] = [];
  for (const block of content) {
    if (!block || typeof block !== "object") continue;
    const typed = block as { type?: unknown; text?: unknown };
    if (typed.type === "text" && typeof typed.text === "string") {
      parts.push(typed.text);
    }
  }
  return parts.join("\n") || null;
};

const lastAssistantMessage = (event: AgentEndEvent): string | undefined => {
  for (let index = event.messages.length - 1; index >= 0; index -= 1) {
    const message = event.messages[index];
    if (!message || typeof message !== "object") continue;

    const typed = message as { role?: unknown; content?: unknown };
    if (typed.role !== "assistant") continue;

    const text = firstString(textFromContent(typed.content));
    if (text) return text;
  }
  return undefined;
};

const sendHook = (
  subcommand: string,
  ctx: ExtensionContext,
  extra: Record<string, unknown> = {}
): void => {
  if (process.env.CMUX_PI_HOOKS_DISABLED === "1") return;
  if (!process.env.CMUX_SURFACE_ID) return;

  const sessionId = firstString(ctx.sessionManager.getSessionId());
  if (!sessionId) return;

  const cwd = firstString(ctx.cwd, process.cwd()) || process.cwd();
  const payload: Record<string, unknown> = {
    session_id: sessionId,
    cwd,
    hook_event_name: eventName(subcommand),
    event: eventName(subcommand),
    ...extra,
  };

  const cmux = process.env.CMUX_PI_CMUX_BIN || "cmux";
  try {
    spawnSync(cmux, ["hooks", "pi", subcommand], {
      input: JSON.stringify(payload),
      encoding: "utf8",
      env: hookEnvironment(cwd),
      stdio: ["pipe", "ignore", "ignore"],
      timeout: 5000,
    });
  } catch {
    // cmux integration is opportunistic; never break Pi if cmux is unavailable.
  }
};

export default function cmuxPiSessionExtension(pi: ExtensionAPI) {
  pi.on("session_start", async (_event, ctx) => {
    sendHook("session-start", ctx);
  });

  pi.on("before_agent_start", async (event, ctx) => {
    sendHook("prompt-submit", ctx, { prompt: event.prompt });
  });

  pi.on("agent_end", async (event, ctx) => {
    sendHook("stop", ctx, {
      last_assistant_message: lastAssistantMessage(event),
    });
  });
}
