#!/usr/bin/env bash
#
# symlink
#
# Creates symlinks for all *.symlink files in the dotfiles directory.
# Called by both bootstrap (initial setup) and dot (updates).

cd "$(dirname "$0")/.."
DOTFILES_ROOT=$(pwd -P)

set -e

. "$DOTFILES_ROOT/lib/log.sh"

info () {
  log_info "$1"
}

success () {
  log_success "$1"
}

link_file () {
  local src=$1 dst=$2

  local overwrite='' backup='' skip=''
  local action=''

  if [ -f "$dst" ] || [ -d "$dst" ] || [ -L "$dst" ]
  then

    if [ "$overwrite_all" = "false" ] && [ "$backup_all" = "false" ] && [ "$skip_all" = "false" ]
    then

      local currentSrc
      currentSrc="$(readlink "$dst")"

      if [ "$currentSrc" = "$src" ]
      then

        skip=true;

      else

        # In non-interactive mode (dot), default to skip
        if [ "$SYMLINK_INTERACTIVE" != "true" ]; then
          info "skipped $src (destination exists, run bootstrap to change)"
          skip=true
        else
          printf "\r  [ \033[0;33m??\033[0m ] File already exists: %s (%s), what do you want to do?\n          [s]kip, [S]kip all, [o]verwrite, [O]verwrite all, [b]ackup, [B]ackup all? " "$dst" "$(basename "$src")"
          read -r -n 1 action
          echo

          case "$action" in
            o )
              overwrite=true;;
            O )
              overwrite_all=true;;
            b )
              backup=true;;
            B )
              backup_all=true;;
            s )
              skip=true;;
            S )
              skip_all=true;;
            * )
              ;;
          esac
        fi

      fi

    fi

    overwrite=${overwrite:-$overwrite_all}
    backup=${backup:-$backup_all}
    skip=${skip:-$skip_all}

    if [ "$overwrite" = "true" ]
    then
      rm -rf "$dst"
      success "removed $dst"
    fi

    if [ "$backup" = "true" ]
    then
      mv "$dst" "${dst}.backup"
      success "moved $dst to ${dst}.backup"
    fi

    if [ "$skip" = "true" ]
    then
      success "skipped $src"
    fi
  fi

  if [ "$skip" != "true" ]  # "false" or empty
  then
    ln -s "$1" "$2"
    success "linked $1 to $2"
  fi
}

install_dotfiles () {
  log_section 'Installing dotfiles'

  local overwrite_all=false backup_all=false skip_all=false

  while IFS= read -r src; do
    dst="$HOME/.$(basename "${src%.*}")"
    link_file "$src" "$dst"
  done < <(find -H "$DOTFILES_ROOT" -maxdepth 2 -name '*.symlink' -not -path '*.git*' | sort)
}

install_dotfiles
