# Brutalist - raw, honest, geometric
"$schema" = 'https://starship.rs/config-schema.json'

format = """
┌─ $directory$git_branch$git_status
└$character"""

[directory]
style = "bold white"
truncation_length = 0
truncate_to_repo = false
format = "[$path]($style) "
home_symbol = "HOME"

[character]
success_symbol = "[▪](bold white)"
error_symbol = "[▪](bold red)"

[git_branch]
symbol = " :: "
style = "white"
format = "[$symbol$branch]($style)"

[git_status]
style = "bold white"
format = " [$all_status$ahead_behind]($style)"
conflicted = "[CONFLICT]"
ahead = "[AHEAD]"
behind = "[BEHIND]"
diverged = "[DIVERGED]"
untracked = "[UNTRACKED]"
stashed = "[STASHED]"
modified = "[MODIFIED]"
staged = "[STAGED]"
renamed = "[RENAMED]"
deleted = "[DELETED]"