# Dieter Rams inspired - "Good design is as little design as possible"
"$schema" = 'https://starship.rs/config-schema.json'

format = """
$directory\
$git_branch\
$git_status\
$line_break\
$character"""

[directory]
style = "white"
truncation_length = 3
truncate_to_repo = true
format = "[$path]($style) "
home_symbol = "~"
read_only = " "

[character]
success_symbol = "[▸](white)"
error_symbol = "[▸](red)"

[git_branch]
symbol = ""
style = "dimmed white"
format = "[$branch]($style) "

[git_status]
style = "dimmed white"
format = "[$all_status$ahead_behind]($style)"
conflicted = "!"
ahead = "↑"
behind = "↓"
diverged = "↕"
untracked = "+"
stashed = ""
modified = "*"
staged = ""
renamed = "→"
deleted = "−"