# Teenage Engineering inspired - playful minimalism with orange accents
"$schema" = 'https://starship.rs/config-schema.json'

format = """
$directory\
$git_branch\
$git_status\
$fill\
$cmd_duration\
$line_break\
$character"""

[directory]
style = "bold white"
truncation_length = 2
truncate_to_repo = true
format = "[$path]($style) "
home_symbol = "~"
read_only = " ro"

[character]
success_symbol = "[◉](bold 214)"  # Orange dot
error_symbol = "[◉](bold red)"

[git_branch]
symbol = ""
style = "214"  # Orange
format = "[$branch]($style) "

[git_status]
style = "dimmed white"
format = "[$all_status$ahead_behind]($style) "
conflicted = "×"
ahead = "↑"
behind = "↓"
diverged = "↕"
untracked = "◦"
stashed = "◫"
modified = "◍"
staged = "◉"
renamed = "»"
deleted = "×"

[cmd_duration]
min_time = 2000
style = "dimmed white"
format = "[$duration]($style) "

[fill]
symbol = " "